import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { getCurrentUser } from "@/lib/auth";
import { formatCurrency } from "@/lib/format";
import { PrintButton } from "@/components/transactions/print-button";

// Standalone print/PDF report (no app shell) — clean for "Save as PDF".
export default async function TransactionsReportPage() {
  const user = await getCurrentUser();
  if (!user) redirect("/login?next=/transactions/report");

  const rows = await prisma.transaction.findMany({
    where: { userId: user.id, deletedAt: null },
    include: { category: { select: { name: true } } },
    orderBy: { occurredAt: "desc" },
  });

  const cur = user.currency;
  let income = 0;
  let expense = 0;
  for (const r of rows) {
    const amt = Number(r.amount);
    if (r.type === "INCOME") income += amt;
    else expense += amt;
  }

  return (
    <main className="mx-auto max-w-4xl bg-white p-8 text-ink print:p-0">
      <header className="flex items-start justify-between border-b border-hairline pb-5">
        <div>
          <h1 className="text-2xl font-black">Transactions report</h1>
          <p className="mt-1 text-sm text-muted">
            {user.name} · {user.email} · {new Date().toLocaleDateString()}
          </p>
        </div>
        <PrintButton label="Print / Save as PDF" />
      </header>

      <section className="mt-5 grid grid-cols-3 gap-4">
        {[
          ["Income", formatCurrency(income, cur)],
          ["Expense", formatCurrency(expense, cur)],
          ["Transactions", String(rows.length)],
        ].map(([k, v]) => (
          <div key={k} className="rounded-lg border border-hairline p-3">
            <p className="text-xs font-bold uppercase text-muted">{k}</p>
            <p className="mt-1 text-lg font-black">{v}</p>
          </div>
        ))}
      </section>

      <table className="mt-6 w-full border-collapse text-left text-sm">
        <thead>
          <tr className="border-b-2 border-ink">
            <th className="py-2 pr-3 font-black">Date</th>
            <th className="py-2 pr-3 font-black">Merchant</th>
            <th className="py-2 pr-3 font-black">Category</th>
            <th className="py-2 pr-3 font-black">Type</th>
            <th className="py-2 text-right font-black">Amount</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.id} className="border-b border-hairline">
              <td className="py-2 pr-3 whitespace-nowrap">{r.occurredAt.toISOString().slice(0, 10)}</td>
              <td className="py-2 pr-3">{r.merchant}</td>
              <td className="py-2 pr-3">{r.category?.name ?? "—"}</td>
              <td className="py-2 pr-3">{r.type}</td>
              <td className="py-2 text-right font-bold">{formatCurrency(Number(r.amount), r.currency)}</td>
            </tr>
          ))}
          {rows.length === 0 && (
            <tr>
              <td colSpan={5} className="py-8 text-center text-muted">No transactions.</td>
            </tr>
          )}
        </tbody>
      </table>

      <footer className="mt-8 text-center text-xs text-muted">Generated by Slipora</footer>
    </main>
  );
}
